# Generated by Django 4.1 on 2022-08-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_tag_user_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes", to="common.ingredient"
            ),
        ),
    ]
